apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: command-handler
          image: username/customer-command-handler:latest
          ports:
            - containerPort: 8084
        - name: policy-handler
          image: username/customer-policy-handler:latest
